### ISSUE TITLE
It won't take my Client ID

### ISSUE THREAD

**Issue by nexus667** [ezeeyahoo/ChromiumSyncEnabler#2]
After taking my API key, it fails to take my client ID.

Error:

Enter correctly: invalid length

**Comment by nexus667** [comment]
I had to change line 139:

GDCI = get_keys('Enter Google Default Client ID: ', list(range(70, 73))

to 

GDCI = get_keys('Enter Google Default Client ID: ', list(range(70, 75))

**Comment by ezeeyahoo** [comment]
https://github.com/ezeeyahoo/ChromiumSyncEnabler/commit/3f235f8070d6d9356d8de00c893d035678573991
