### ISSUE TITLE
您好，跑完这个终端里显示Original binary missing! Reinstall App or report bug是为什么呀

### ISSUE THREAD

**Issue by TT1890155** [ezeeyahoo/ChromiumSyncEnabler#3]
您好，跑完这个终端里显示Original binary missing! Reinstall App or report bug是为什么呀，求解=。=完全小白

**Comment by TT1890155** [comment]
额嗯。我的app位置和名字与预设的可能不一样，现在解决了。现在我可以打开chromium的登录界面，然后下一步怎么都点不动，或许是我自己设置的API有问题吗？然后我去那个云台的界面，登录处输完邮箱的下一步也点不动。我再回头看用chrom的也是点不动下一步这种情况，或许您了解原因吗

**Comment by arminanton** [comment]
> 您好，跑完这个终端里显示Original binary missing! Reinstall App or report bug是为什么呀，求解=。=完全小白 `(Translation) Hello, after running this in the terminal, the Original binary seems to be missing! "Reinstall App" or "report bug" message is displayed; why is it? How to solve it? (=.=) I'm a complete noob (unfamiliar with this)`

原来的二进制文件没有丢失，而是重命名为位于 Chromium_orig_bin 下的 /Application/Chromium.app/Contents/MacOS/。

文件 "Chromium" 的原始名称被用于在运行之前将密钥注入应用程序的脚本。

`(Translation) The original binary is not lost, but renamed to Chromium_orig_bin located under /Application/Chromium.app/Contents/MacOS/. The original name of the file "Chromium" was used for a script that injects the keys into the application before running.`


--------------
> 额嗯。我的app位置和名字与预设的可能不一样，现在解决了。现在我可以打开chromium的登录界面，然后下一步怎么都点不动，或许是我自己设置的API有问题吗？然后我去那个云台的界面，登录处输完邮箱的下一步也点不动。我再回头看用chrom的也是点不动下一步这种情况，或许您了解原因吗 `(Translation) Hmm. The location and name of my app may not be the same as the default one, but it's solved now. Now I can open the login interface of chromium, but I can't click on the next step. Maybe there is a problem with the API that I set myself? When I went to the Gmail login, it didn't go to the next step after entering the mailbox at the login. When I go back, I can't go to the next step (of activating sync) like when I use Chrome. Maybe you know the reason?`

执行 Chromium 脚本后，实际浏览器将打开，但不会自动激活 Google 同步。您必须导航到“设置”（在 Chromium 浏览器中），然后单击“Google 帐户”选项卡下的“打开同步”。
`(Translation) After executing the Chromium script, the actual browser will open, but Google Sync will not be automatically activated. You must navigate to Settings (in the Chromium browser) and click "Turn on sync" under the "Google Accounts" tab.`


----------
Pardon my Chinese as I am using Google Translator to reply.
请原谅我的中文，因为我正在使用谷歌翻译回复。
