### ISSUE TITLE
Hyperlinks Not Working Outside Chromium

### ISSUE THREAD

**Issue by ckabalan** [ezeeyahoo/ChromiumSyncEnabler#4]
Using latest version of the tool, sync works fine, however I can't get links outside of Chromium to open. When I use spotlight search or click links in other applications (like Outlook) nothing happens.

Looks like according to the commit history this should be working, but I'm not sure how to troubleshoot this.

**Comment by ezeeyahoo** [comment]
get me output of
```$cat /Applications/Chromium.app/Contents/MacOS/Chromium```

**Comment by ezeeyahoo** [comment]
reopen if you want to update
