### ISSUE TITLE
Hyperlinks do not work outside Chromium

### ISSUE THREAD

**Issue by Coolfalcon** [ezeeyahoo/ChromiumSyncEnabler#5]
I am having the same problem as in a previously closed issue. I set chromium as my default browser, and by clicking any links outside chromium, nothing happens, e.g. in Mail, Messages, notes and other third-party apps. Right click -> "open with Chromium" does not work either. My chromium file has the scripts as follows, with the keys masked by ****. Thanks!

```sh
#!/bin/bash

# Set up environment variables
export GOOGLE_API_KEY="****"
export GOOGLE_DEFAULT_CLIENT_ID="****"
export GOOGLE_DEFAULT_CLIENT_SECRET="****"

# Launch Chromium
exec /Applications/Chromium.app/Contents/MacOS/Chromium_orig_bin "$@"
```

**Comment by ezeeyahoo** [comment]
there is a dot missing exec /Applications ---> exec ./Applications

```
# Launch Chromium
exec ./Applications/Chromium.app/Contents/MacOS/Chromium_orig_bin "$@"
```

**Comment by Coolfalcon** [comment]
Solved! Thank you

**Comment by ezeeyahoo** [comment]
Did you accidentally got that dot deleted?

If not you can provide me garbled input replace letter, number, symbol with random letter, numner, symbol respectively. It will help me in debugging the problem.

Thanks

**Comment by Coolfalcon** [comment]
> Did you accidentally got that dot deleted?
> 
> If not you can provide me garbled input replace letter, number, symbol with random letter, numner, symbol respectively. It will help me in debugging the problem.
> 
> Thanks

I believe so. I had copied, pasted and edited the content a few times. It was probably me. Thanks.
